#!/bin/bash

if [ -d "$1" ]; then
  echo "$1 exists."
else
  mkdir $1 && cd $1
  masscan -p 5555 0.0.0.0/0 --exclude 255.255.255.255 --rate=10000 -oX $1_masscan
  cut -d '"' -f 4 $1_masscan | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'| awk '{print $1 ":5555"}' > $1_ipsonly        cat $1_ipsonly | parallel -j 20 adb connect {} | tee $1_teeout
  adb devices | grep device | grep -v devices > $1_working
  cat $1_teeout | grep connected > $1_working_tee
  adb disconnect
fi
