#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 directory_name"
    exit 1
fi

if [ -d "$1" ]; then
    echo "$1 already exists. Please choose a different directory name."
    exit 1
fi

mkdir "$1" && cd "$1" || { echo "Failed to create directory $1"; exit 1; }


# Check if masscan is installed
if ! command -v masscan &> /dev/null
then
    echo "masscan could not be found. Aborting."
    exit 1
fi

# Run masscan
sudo masscan -p 5555 0.0.0.0/0 --exclude 255.255.255.255 --rate=10000 -oX "$1_masscan.xml" || { echo "Failed to run masscan"; exit 1; }

# Extract IP addresses from masscan output
cut -d '"' -f 4 "$1_masscan.xml" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | awk '{print $1 ":5555"}' > "$1_ips_only.txt" || { echo "Failed to extract IP addresses"; exit 1; }

# Connect to devices in parallel
cat "$1_ips_only.txt" | parallel -j 20 adb connect {} | tee "$1_connect_output.txt" || { echo "Failed to connect to devices"; exit 1; }

# Get list of connected devices
adb devices | grep device | grep -v devices | awk '{print $1}' > "$1_working.txt" || { echo "Failed to get list of connected devices"; exit 1; }

# Save output of connection attempts
cat "$1_connect_output.txt" | grep connected > "$1_working_tee.txt"

adb disconnect

echo "Done."
